# Generated by Django 5.2.12 on 2026-04-04 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarketDataSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=4, max_digits=12)),
                ('open_price', models.DecimalField(decimal_places=4, max_digits=12, null=True)),
                ('high', models.DecimalField(decimal_places=4, max_digits=12, null=True)),
                ('low', models.DecimalField(decimal_places=4, max_digits=12, null=True)),
                ('volume', models.BigIntegerField(null=True)),
                ('market_cap', models.BigIntegerField(null=True)),
                ('pe_ratio', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('dividend_yield', models.DecimalField(decimal_places=4, max_digits=6, null=True)),
                ('data_source', models.CharField(default='yahoo_finance', max_length=50)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-fetched_at'],
                'get_latest_by': 'fetched_at',
            },
        ),
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('source', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('published_at', models.DateTimeField()),
                ('summary', models.TextField(blank=True)),
                ('sentiment_score', models.FloatField(blank=True, help_text='Sentiment score from -1.0 (bearish) to 1.0 (bullish)', null=True)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
    ]
