# Generated by Django 5.2.12 on 2026-04-04 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('market_data', '0001_initial'),
        ('research', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketdatasnapshot',
            name='ticker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_snapshots', to='research.stockticker'),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='ticker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='news_articles', to='research.stockticker'),
        ),
    ]
