# Generated by Django 5.2.12 on 2026-04-04 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0001_initial'),
        ('research', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentrun',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_runs', to='research.researchreport'),
        ),
    ]
